export default {
    VIEW_ACTION: "VIEW_ACTION",
    CREATE_NOTE: "CREATE_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    DESTROY_NOTE: "DESTROY_NOTE",
    REORDER_NOTES: "REORDER_NOTES",
    CREATE_LANE: "CREATE_LANE",
    UPDATE_LANE: "UPDATE_LANE",
    DESTROY_LANE: "DESTROY_LANE",
    REORDER_LANES: "REORDER_LANES"
};